# Generated by Django 2.2 on 2022-02-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefeeditem',
            name='file_uploaded',
            field=models.FileField(blank=True, default='', upload_to='documents/%Y/%m/%d/'),
        ),
    ]
